services:

  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-net

  agent1:
    image: jenkins/agent:latest
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=agent1
      - JENKINS_SECRET=${AGENT1_SECRET}
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins
    networks:
      - jenkins-net

  agent2:
    image: jenkins/agent:latest
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=agent2
      - JENKINS_SECRET=${AGENT2_SECRET}
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins
    networks:
      - jenkins-net

  jenkins-cli:
    image: jenkins/jenkins:lts-jdk21
    user: root
    entrypoint: []
    command: >
      sh -c "
        until curl -sf http://jenkins:8080/login > /dev/null; do
          echo 'Waiting for Jenkins...' && sleep 5
        done &&
        curl -s http://jenkins:8080/jnlpJars/jenkins-cli.jar -o /tmp/jenkins-cli.jar &&
        java -jar /tmp/jenkins-cli.jar -s http://jenkins:8080 -auth admin:admin create-node agent1 < /tmp/agent1.xml &&
        java -jar /tmp/jenkins-cli.jar -s http://jenkins:8080 -auth admin:admin create-node agent2 < /tmp/agent2.xml
      "
    volumes:
      - ./nodes/agent1.xml:/tmp/agent1.xml:ro
      - ./nodes/agent2.xml:/tmp/agent2.xml:ro
    depends_on:
      - jenkins
    restart: "no"
    networks:
      - jenkins-net

  ssh-agent:
    image: jenkins/ssh-agent:latest
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB6M7LqNvlzcmU25zdsHN83cxwZvp8BVnPyrGOxvcJA jenkins-ssh-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins
    networks:
      - jenkins-net

networks:
  jenkins-net:

volumes:
  jenkins_home:
