pipeline {
    agent any

    environment {
        REGISTRY   = 'localhost:5000'
        IMAGE_NAME = 'water-app'
    }

    stages {

        stage('Checkout') {
            steps {
                git url: 'https://github.com/turban-sizzle/fluffy-octo-sniffle.git',
                    branch: 'main'
            }
        }

        stage('Tests') {
            agent {
                docker {
                    image 'python:3.11'
                    reuseNode true
                }
            }
            steps {
                sh 'pip install -r requirements.txt'
                sh 'pytest'
            }
        }

        stage('Build Image') {
            steps {
                sh "docker build -t ${REGISTRY}/${IMAGE_NAME}:${BUILD_NUMBER} ."
                sh "docker tag  ${REGISTRY}/${IMAGE_NAME}:${BUILD_NUMBER} ${REGISTRY}/${IMAGE_NAME}:latest"
            }
        }
    }
}
